# Generated by Django 2.0.3 on 2018-03-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180325_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_id',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Company'),
        ),
    ]
