# Generated by Django 2.0.3 on 2018-03-25 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180325_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
